# Generated by Django 3.1.2 on 2020-10-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=64)),
                ('phone_number', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('birth', models.CharField(max_length=32, null=True)),
                ('kakao_id', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
